### ISSUE TITLE
New column-length default?

### ISSUE THREAD

**Issue by henryiii** [tox-dev/pyproject-fmt-rust#29]
I'd like to propose possibly changing the default of `column-length` (to 80 or 88 or 120, I don't care which). When it's set, Taplo acts like black; a trailing comma forces one-per-line, but leaving off the trailing comma allows lists under the column-length to fit on one line. It's a backward compatible change: existing files formatted with pyproject-fmt will not change, since they have the trailing comma added already.

Left alone:
```toml
a = [
  "b",
]
```

Now supported too with the default change:
```toml
a = [ "b" ]
```

A lot of pyproject.toml doesn't change rapidly, so this still reduces the LoC and visual clutter quite a bit. Things that do (like classifiers) will still be always multiline, and users can pick based on the trailing comma.

Thoughts?

(If not, I can just always set this config option, I just thought being more black-like out of the box would be nice)

**Comment by gaborbernat** [comment]
I'm fine with this let's do 120.
