### ISSUE TITLE
tox.ini: pyproject_fmt -> pyproject_fmt_rust

### ISSUE THREAD

**Issue by mtelka** [tox-dev/pyproject-fmt-rust#6]
I believe `pyproject_fmt` should be changed to `pyproject_fmt_rust` here: https://github.com/tox-dev/pyproject-fmt-rust/blob/main/tox.ini#L28C82-L28C95

**Comment by gaborbernat** [comment]
Good catch, PR welcome 🤗

**Comment by gaborbernat** [comment]
https://github.com/tox-dev/pyproject-fmt-rust/commit/6ed00bbcb1b639fadd4a5c0245c76a268e65a3fc
